INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'portfolio',
    'portfolio.app.education',
    'portfolio.app.experience',
    'portfolio.app.projects',
    'portfolio.app.skills',
    'portfolio.app.companies',
    'portfolio.app.courses',
    'portfolio.app.schools',
]
