# Generated by Django 3.0.4 on 2020-04-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, help_text="Description of the company's industry and work.", max_length=1024, null=True),
        ),
    ]
