# Generated by Django 3.0.4 on 2020-04-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='include_in_resume',
            field=models.BooleanField(default=True, help_text='Determines whether or not the experience will be included in the auto generated resume.'),
        ),
    ]
