# Generated by Django 3.0.4 on 2020-04-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='short_title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
