# Generated by Django 3.0.4 on 2020-03-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name_plural': 'Experience History'},
        ),
    ]
