# Generated by Django 3.0.4 on 2020-03-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='description',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='short_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
