# Generated by Django 3.0.4 on 2020-04-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='showcase_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
