# Generated by Django 3.0.4 on 2020-03-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfile',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='name',
            field=models.CharField(help_text='Verbose name for the file that will be used for links accessing the file.', max_length=64, unique=True),
        ),
    ]
