# Generated by Django 3.0.4 on 2020-04-09 00:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='showcase_description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
