# Generated by Django 3.0.4 on 2020-04-09 02:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
