# Generated by Django 3.0.4 on 2020-03-28 02:09

from django.db import migrations, models
import portfolio.app.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(null=True, upload_to=portfolio.app.projects.models.upload_to),
        ),
    ]
