# Generated by Django 3.0.4 on 2020-04-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='relative_order',
            field=models.IntegerField(default=0),
        ),
    ]
