# Generated by Django 3.0.4 on 2020-03-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200330_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='caption',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='long_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
