# Generated by Django 3.0.4 on 2020-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200330_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_alone',
            field=models.BooleanField(default=True),
        ),
    ]
