# Generated by Django 3.0.4 on 2020-04-19 03:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_optional_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='include_in_resume',
            field=models.BooleanField(default=True, help_text='Determines whether or not the project will be included in the auto generated resume.'),
        ),
        migrations.AddField(
            model_name='project',
            name='resume_description',
            field=models.CharField(blank=True, help_text='If included, will be used instead of the description for the auto generated resume.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Required if the project is tied to an education or an experience.', null=True),
        ),
    ]
