# Generated by Django 3.0.4 on 2020-03-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_display_alone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='display_alone',
            field=models.BooleanField(default=True, help_text="Determines whether or not the project will be displayed on the projects page as it's own item."),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.CharField(help_text='Description of the project limited to 1024 characeters.  Will be used when the project is listed as its own item on the projects page.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='Description of the project limited to 256 characters.  Will be used when the project is listed under an education or experience.', max_length=256),
        ),
    ]
