# Generated by Django 3.0.4 on 2020-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200330_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.CharField(default='None', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='None', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='short_description',
            field=models.CharField(default='None', max_length=128),
            preserve_default=False,
        ),
    ]
