# Generated by Django 3.0.4 on 2020-03-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200330_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='short_description',
            field=models.CharField(max_length=256),
        ),
    ]
