# Generated by Django 3.0.4 on 2020-04-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_resume_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='resume_description',
            field=models.CharField(blank=True, help_text='If included, will be used instead of the description for the auto generated resume.', max_length=512, null=True),
        ),
    ]
