# Generated by Django 3.0.4 on 2020-03-18 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=2)),
                ('logo', models.ImageField(null=True, upload_to='upload_to')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('degree', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=64)),
                ('minor', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('concentration', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('projects', models.ManyToManyField(blank=True, help_text='Projects worked on during education.', related_name='education_education_projects', to='projects.Project')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.School')),
            ],
        ),
    ]
