# Generated by Django 3.0.4 on 2020-03-25 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '__first__'),
        ('schools', '__first__'),
        ('courses', '__first__'),
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=64)),
                ('gpa', models.FloatField(null=True)),
                ('minor', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('concentration', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, help_text='Courses taken during education.', related_name='education_education_courses', to='courses.Course')),
                ('projects', models.ManyToManyField(blank=True, help_text='Projects worked on during education.', related_name='education_education_projects', to='projects.Project')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
                ('skills', models.ManyToManyField(blank=True, help_text='Skilled worked on during education.', related_name='education_education_skills', to='skills.Skill')),
            ],
            options={
                'verbose_name_plural': 'Education History',
            },
        ),
    ]
