# Generated by Django 3.0.4 on 2020-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
