# Generated by Django 3.0.4 on 2020-03-18 15:22

from django.db import migrations, models
import portfolio.app.education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(null=True, upload_to=portfolio.app.education.models.upload_to),
        ),
    ]
