# Generated by Django 3.0.4 on 2020-03-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('education', '0005_education_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skilled worked on during education.', related_name='education_education_skills', to='skills.Skill'),
        ),
        migrations.AlterField(
            model_name='education',
            name='concentration',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
