# Generated by Django 3.0.4 on 2020-03-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Courses taken during education.', related_name='education_education_courses', to='education.Course'),
        ),
    ]
