# Generated by Django 3.0.4 on 2020-04-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='value',
            new_name='comment',
        ),
    ]
