# Generated by Django 3.0.4 on 2020-04-04 00:54

from django.db import migrations, models
import portfolio.app.profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headshot',
            field=models.ImageField(null=True, upload_to=portfolio.app.profile.models.upload_headshot_to),
        ),
    ]
