# Generated by Django 3.0.4 on 2020-04-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.CharField(default='None', max_length=2048),
            preserve_default=False,
        ),
    ]
