# Generated by Django 3.0.4 on 2020-04-19 03:35

from django.db import migrations, models
import portfolio.app.profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(default='', upload_to=portfolio.app.profile.models.upload_logo_to),
            preserve_default=False,
        ),
    ]
