# Generated by Django 3.0.4 on 2020-04-19 03:42

from django.db import migrations, models
import portfolio.app.profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='headshot',
            field=models.ImageField(default='', upload_to=portfolio.app.profile.models.upload_headshot_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
