# Generated by Django 3.0.4 on 2020-03-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experience', '__first__'),
        ('education', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('educations', models.ManyToManyField(blank=True, to='education.Education')),
                ('experiences', models.ManyToManyField(blank=True, to='experience.Experience')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
